name: cp2k
description: CP2K 2024.1 and all the tools and libraries required to built CP2K on multicore.
store: /user-environment
spack:
  repo: https://github.com/spack/spack.git
  commit: v0.21.2 
modules: True
