sirius:
  compiler:
      - toolchain: gcc
        spec: gcc@12.3
  unify: true
  specs:
  - cmake
  - ninja
  - pkgconfig
  - cuda@12.4
  - gsl +external-cblas
  - openblas threads=openmp
  - fftw
  - netlib-scalapack
  - libxc@6 ~cuda
  - spglib
  - hdf5 +hl
  - elpa
  - dla-future@0.7.3 +miniapps +mpi_gpu_aware +hdf5
  - umpire
  # COSTA dependencies
  - costa
  - tiled-mm
  # SIRIUS
  - gsl@2.7.1 # 2.8 fails to build
  - sirius@7.6.1 ~python +tests +fortran +scalapack +elpa +dlaf
  variants:
  - +openmp
  - +mpi
  - +cuda
  - cuda_arch=90
  - build_type=Release
  mpi:
    spec: cray-mpich
    gpu: cuda
  views:
    sirius:
      link: roots
    develop:
      link: roots
      exclude: ["sirius"]
