cp2k:
  compiler:
  - toolchain: gcc
    spec: gcc@12.3
  unify: true
  specs:
  - cmake
  - ninja
  - openblas
  - netlib-scalapack
  - libxc@6
  - libint
  - spglib
  - spla
  - elpa
  - libxsmm
  - plumed
  # DLA-Future
  - pika
  - dla-future +miniapps
  - dla-future-fortran
  # COSMA dependencies (need to be in the develop view)
  - costa
  - cosma
  # SIRIUS dependencies (need to be in the develop view)
  - hdf5
  - spfft
  - sirius
  # CP2K
  - dbcsr@2.8.0
  - cp2k@2025.1 +spglib +cosma +spla +elpa +dlaf +sirius +plumed
  variants:
    - +mpi
    - +openmp
    - build_type=Release
    - ~cuda
    - ~rocm
  mpi:
    spec: cray-mpich@8.1.30
  views:
    develop:
      link: roots
      exclude: ["cp2k"]
    cp2k:
      link: roots
